[package]
name = "relay-transport"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "MPL-2.0"
repository.workspace = true
homepage.workspace = true
description = "Provider-neutral bounded native transport interface for RELAY"
publish = false

[dependencies]

[lints]
workspace = true

[dev-dependencies]
relay-protocol = { version = "=0.1.0", path = "../relay-protocol" }
prost.workspace = true
